### ISSUE TITLE
Macro std::matches  parse exception

### ISSUE THREAD

**Issue by Aurora-up** [lukaslueg/macro_railroad_ext#16] opened 2022-12-05 09:06 UTC
![image](https://user-images.githubusercontent.com/79568927/205597011-99981438-3496-459d-b0e5-f82eb6c1acec.png)

**Comment by bjorn3** [comment] 2022-12-05 09:55
Duplicate of https://github.com/lukaslueg/macro_railroad/issues/25

**Comment by lukaslueg** [comment] 2022-12-05 16:18
Closing this as a dupe of #25. I won't have time to work on this, so if anyone wants to work on this, help would be greatly appreciated. Please see [here](https://github.com/lukaslueg/macro_railroad/issues/25#issuecomment-1094025244) for some guidance

**Closed as not planned** 2022-12-05 16:18 UTC
